#!/bin/bash

# Color the prompt
export PS1='\033[92m\w\033[0m:\n∴ '

# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

alias haha='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias aga='ag -s --color-path "1;36" --ignore={public/_assets/,vendor/,thumbprint/legacy-js/vendor/,thumbprint/legacy-js/admin/,public/media/,node_modules/,dist/}'
alias chrome='open -a "Google Chrome"'

alias lg='~/.okta/logind'
alias okl='okta-login admin'

# iOS alias(es)
alias podi='bundle exec pod install || bundle exec pod install --repo-update'

# Added manually for homebrew
export PATH=/usr/local/bin:$PATH

# Added manually for Thumbtack's phpcs
export PHP_COMPOSER_VENDOR_PATH="$HOME/Thumbtack/website/vendor/php/composer/vendor/bin"
export PATH=$PHP_COMPOSER_VENDOR_PATH:$PATH

# Manually added for Git (installed via Homebrew)
source '/usr/local/etc/bash_completion.d/git-completion.bash'

export GOPATH="$HOME/go-work"
export PATH=$GOPATH/bin:$PATH


# Manually added for iOS dev env setup
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

# Added per the yoda installation instructions
export PATH=/usr/local/go/bin:$PATH
export PATH=/usr/local/opt/postgresql@9.6/bin:$PATH
export TT_WEBSITE_DIR=$HOME/Thumbtack/website
export TT_TOPHAT_DIR=/Users/bjensen/Thumbtack/tophat
export TT_PG_SCHEMA_DIR=$HOME/Thumbtack/postgres-schema

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# eval "$(rbenv init -)"

okta-login() {
    if [[ -z "$1" ]]; then
        >&2 echo 'Usage: okta-login <profile>';
        return 1;
    fi
    export OKTA_PROFILE=$1
    export AWS_PROFILE=$1_source
    ~/.okta/login
}
