#!/bin/bash

# Color the prompt
export PS1='\033[92m\w\033[0m:\n∴ '

# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

export NVM_DIR="/Users/bjensen/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

alias haha='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias aga='ag --ignore={public/_assets/,vendor/,thumbprint/legacy-js/vendor/,thumbprint/legacy-js/admin/,public/media/,thumbprint/legacy-js/labs/}'
alias chrome='open -a "Google Chrome"'

# Added manually for homebrew
export PATH=/usr/local/bin:$PATH

# Added manually for Thumbtack's phpcs
export PHP_COMPOSER_VENDOR_PATH="$HOME/Thumbtack/website/vendor/php/composer/vendor/bin"
export PATH=$PHP_COMPOSER_VENDOR_PATH:$PATH

# Manually added for Git (installed via Homebrew)
source '/usr/local/etc/bash_completion.d/git-completion.bash'

# Unneeded because PHP is already correctly symlinked from /usr/local/bin (?)
# export PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"

# auto_uploader
alias autoupload="~/Thumbtack/auto_uploader/auto_uploader"
# tt-sync
alias myttsync="ttsync --source ~/Thumbtack/website/ --destination farnsworth-bjensen.dev-internal:/srv/thumbtack/code/"
# monorepo-builder
alias mymrb="CONVEYOR_PG_HOST='conveyor-postgres' CONVEYOR_PG_SSL_MODE='disable' CONVEYOR_PG_PORT=5432 CONVEYOR_PG_USER='conveyor' CONVEYOR_PG_NAME='conveyor' CONVEYOR_PG_PASS='conveyor' monorepo-builder -s conveyor --staging-ground ~/testing-grounds/ -p 3000"
# docker start new terminal
alias dockerterm="docker exec -i -t"
# dev experiment service ssh tunnel
alias exptun="ssh -N us-west-2.ssh.thumbtack.com -L 9000:dev-experiment-web.thumbtack.io:80"

alias sshf="ssh farnsworth-bjensen.dev-internal"
alias sshf2="ssh farnsworth-bjensen-2.dev-internal"
alias sshtun='ssh -R 9000:localhost:9000 farnsworth-bjensen.dev-internal'

export GOPATH="$HOME/go-work"
export PATH=$GOPATH/bin:$PATH

export AWS_ACCESS_KEY_ID=AKIAJTCPVUKIZU6VZJYQ
export AWS_SECRET_ACCESS_KEY=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
export CONVEYOR_PG_HOST="conveyor-postgres"